<html>
    <head>
        <title>tuta004</title>
    </head>
    <body>นายเมธาสิทธิ์ นาสิงห์ขันธ์<p>เลขที่6 มัถยมศึกษาปีที่5/2</p></body>
    <table> <table border="4">
        <tr>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
        <tr>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
        <tr>
            <td>9</td>
            <td>10</td>
            <td>11</td>
            <td>12</td>
        <tr>
            <td>13</td>
            <td>14</td>
            <td>15</td>
            <td>16</td>
         <tr>
            <td>17</td>
            <td>18</td>
            <td>19</td>
            <td>20</td>
        <tr>
            <td>22</td>
            <td>23</td>
            <td>24</td>
            <td>25</td>
        <tr>
            <td>26</td>
            <td>27</td>
            <td>28</td>
            <td>29</td>
        <tr>
            <td>30</td>
            <td>31</td>
            <td>32</td>
            <td>33</td>
        <tr>
            <td>34</td>
            <td>35</td>
            <td>36</td>
            <td>37</td>
        <tr>
            <td>38</td>
            <td>39</td>
            <td>40</td>
            <td>41</td>
        <tr>
            <td>41</td>
            <td>42</td>
            <td>43</td>
            <td>44</td>
         </able>
</html>
